raw <- system.file("extdata", "howell.csv", package = "bioanth")
howell <- read.csv(raw, stringsAsFactors=FALSE)
howell$Sex <- factor(howell$Sex)
howell$Population <- factor(howell$Population)
howell$PopNum <- factor(howell$PopNum)
howell <- dplyr::tbl_df(howell)
